name: issue opened

on: 
  issues:
    types:
      - opened
      - unlocked

jobs:
  lock-issue:
    runs-on: ubuntu-latest
    steps:
      - name: print event
        run: echo "${{ toJson(github.event) }}"
      - uses: maxkomarychev/lock-issue@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.id }}
          lock-reason: off-topic
